const entity = (key, domains) => ({ key, type: 'entity', domains });
export const definition = {
  id: 'sauna', key: 'hads_sauna_config',
  defaults: { title: 'Badstue', user_entity: '', temperature_entity: '', extra_1_entity: '', extra_1_label: 'Luftfuktighet', extra_2_entity: '', extra_2_label: 'Status', subtitle: 'Senk skuldrene. Nyt øyeblikket.', logo_url: '', background_url: '', background_position: 65, logo_height: 48, surface: '#f5f2e9', ink: '#34483e', accent: '#74876a', photo_strength: 100, language: 'no', appearance: 'light', animate: false, style: 'sauna', timezone: '', show_seconds: false },
  fields: [
    { key: 'title' }, entity('user_entity', ['sensor', 'input_text']), entity('temperature_entity', ['sensor', 'climate']),
    entity('extra_1_entity', ['sensor', 'binary_sensor', 'input_number', 'input_text', 'switch']), { key: 'extra_1_label' },
    entity('extra_2_entity', ['sensor', 'binary_sensor', 'input_number', 'input_text', 'switch']), { key: 'extra_2_label' },
    { key: 'subtitle' }, { key: 'logo_url', maxLength: 4096, hint: 'urlHint' },
    { key: 'logo_height', type: 'number', min: 24, max: 100, step: 1 },
    { key: 'background_url', maxLength: 4096, hint: 'backgroundHint' },
    { key: 'background_position', type: 'number', min: 0, max: 100, step: 1 },
    { key: 'photo_strength', type: 'number', min: 0, max: 100, step: 1 },
    { key: 'surface', type: 'color' }, { key: 'ink', type: 'color' }, { key: 'accent', type: 'color' },
    { key: 'language', options: [['no', 'norwegian'], ['en', 'english'], ['auto', 'auto']] },
    { key: 'timezone', hint: 'timezoneHint' }, { key: 'show_seconds', type: 'checkbox' },
  ],
  copy: {
    no: { sauna: 'Badstue', saunaKicker: 'Et øyeblikk for deg', title: 'Navn på badstuen', user_entity: 'Sensor med gjestens navn', temperature_entity: 'Temperatur i badstuen', extra_1_entity: 'Ekstra verdi 1', extra_1_label: 'Overskrift for verdi 1', extra_2_entity: 'Ekstra verdi 2', extra_2_label: 'Overskrift for verdi 2', subtitle: 'Tekst under velkomsten', logo_url: 'Logo fra URL', logo_height: 'Logohøyde (px)', background_url: 'Eget bakgrunnsbilde fra URL', background_position: 'Bildets horisontale fokus (0–100)', photo_strength: 'Bildets synlighet (%)', surface: 'Bakgrunnsfarge', ink: 'Tekstfarge', accent: 'Detaljfarge', urlHint: 'Bruk https://… eller /local/… fra Home Assistant. Tomt felt viser symbolet.', backgroundHint: 'Tomt felt bruker det medfølgende badstuebildet.', norwegian: 'Norsk', english: 'English', timezone: 'Tidssone (valgfritt)', timezoneHint: 'F.eks. Europe/Oslo. Tomt felt følger Home Assistant, deretter nettleseren.', show_seconds: 'Vis sekunder', welcome: 'Velkommen', temperature: 'I badstuen nå', dateTime: 'Dato og klokkeslett', updated: 'Målt', configure: 'Velg sensorer', connect: 'Velg temperatursensor i innstillingene.', noReading: 'Ingen måling', logoError: 'Logoen kunne ikke lastes. Sjekk URL-en.', backgroundError: 'Bakgrunnsbildet kunne ikke lastes. Viser standardbildet.', urlError: 'Bildeadressen må være en HTTP(S)-URL eller en sti som /local/bilde.jpg.', zoneError: 'Ugyldig tidssone. Bruker Home Assistants eller nettleserens tidssone.', entityHint: 'Koble til sensorene dine og tilpass badstuens visuelle uttrykk.' },
    en: { sauna: 'Sauna', saunaKicker: 'A moment for yourself', title: 'Sauna name', user_entity: 'Guest name sensor', temperature_entity: 'Sauna temperature', extra_1_entity: 'Extra reading 1', extra_1_label: 'Reading 1 heading', extra_2_entity: 'Extra reading 2', extra_2_label: 'Reading 2 heading', subtitle: 'Welcome subtitle', logo_url: 'Logo URL', logo_height: 'Logo height (px)', background_url: 'Custom background image URL', background_position: 'Horizontal image focus (0–100)', photo_strength: 'Image visibility (%)', surface: 'Background colour', ink: 'Text colour', accent: 'Detail colour', urlHint: 'Use https://… or /local/… in Home Assistant. Leave empty for the symbol.', backgroundHint: 'Leave empty to use the included sauna photograph.', norwegian: 'Norsk', english: 'English', timezone: 'Time zone (optional)', timezoneHint: 'For example Europe/Oslo. Empty follows Home Assistant, then the browser.', show_seconds: 'Show seconds', welcome: 'Welcome', temperature: 'Inside the sauna', dateTime: 'Date and time', updated: 'Measured', configure: 'Choose sensors', connect: 'Choose a temperature sensor in settings.', noReading: 'No reading', logoError: 'Could not load the logo. Check its URL.', backgroundError: 'Could not load the background. Showing the included image.', urlError: 'The image address must be an HTTP(S) URL or a path such as /local/image.jpg.', zoneError: 'Invalid time zone. Using Home Assistant or browser time.', entityHint: 'Connect your sensors and make the sauna feel like your own.' },
  },
};
