const option = (key, options, extra = {}) => ({ key, options: options.map((value) => [value, value]), ...extra });
const entity = (key, domains, extra = {}) => ({ key, type: 'entity', domains, ...extra });
const commonDefaults = { title: '', language: 'auto', appearance: 'auto', animate: true };
const commonFields = [
  { key: 'title' }, option('language', ['auto', 'no', 'en']), option('appearance', ['auto', 'light', 'dark']),
  { key: 'accent', type: 'color' }, { key: 'animate', type: 'checkbox' },
];
const commonCopy = { no: { no: 'Norsk', en: 'English' }, en: { no: 'Norsk', en: 'English' } };
function definition(id, defaults, fields, copy, size) {
  return { id, key: 'hads_' + id + '_config', defaults: { ...commonDefaults, ...defaults }, fields: [...fields, ...commonFields], copy: { no: { ...commonCopy.no, ...copy.no }, en: { ...commonCopy.en, ...copy.en } }, size };
}
export const definitions = {
  cover: definition('cover', { entity: '', style: 'slats', accent: '#728557', show_tilt: true }, [
    entity('entity', ['cover']), option('style', ['slats', 'curtains', 'garage']), { key: 'show_tilt', type: 'checkbox' },
  ], {
    no: { cover: 'Lys inn. Ro ned.', coverKicker: 'Cover control', entity: 'Persienne, gardin eller port', slats: 'Persienner', curtains: 'Gardiner', garage: 'Garasjeport', show_tilt: 'Vis lamellvinkel når støttet', open: 'Åpen', closed: 'Lukket', opening: 'Åpner', closing: 'Lukker', openAction: 'Åpne', closeAction: 'Lukk', stop: 'Stopp', position: 'Åpningsgrad', tilt: 'Lamellvinkel', sending: 'Sender …', release: 'Slipp for å stille posisjonen.', coverNote: '0% er lukket · 100% er helt åpen' },
    en: { cover: 'Let the day in.', coverKicker: 'Cover control', entity: 'Blind, curtain or door', slats: 'Slats', curtains: 'Curtains', garage: 'Garage', show_tilt: 'Show tilt when supported', open: 'Open', closed: 'Closed', opening: 'Opening', closing: 'Closing', openAction: 'Open', closeAction: 'Close', stop: 'Stop', position: 'Open position', tilt: 'Slat tilt', sending: 'Sending …', release: 'Release to set the position.', coverNote: '0% is closed · 100% is fully open' },
  }, { width: 580, height: 480 }),
  room: definition('room', { style: 'lounge', accent: '#7b8b74', temperature: '', humidity: '', co2: '', presence: '', action_1: '', action_2: '', action_3: '', action_1_label: '', action_2_label: '', action_3_label: '' }, [
    option('style', ['lounge', 'blueprint', 'minimal']), entity('temperature', ['sensor'], { deviceClasses: ['temperature'] }), entity('humidity', ['sensor'], { deviceClasses: ['humidity'] }), entity('co2', ['sensor'], { deviceClasses: ['carbon_dioxide'] }), entity('presence', ['binary_sensor'], { deviceClasses: ['occupancy', 'presence', 'motion'] }),
    ...[1, 2, 3].flatMap((n) => [entity('action_' + n, ['light', 'switch', 'scene', 'script', 'input_boolean']), { key: 'action_' + n + '_label' }]),
  ], {
    no: { room: 'Et rom å lande i.', roomKicker: 'Room control', lounge: 'Stue', blueprint: 'Romskisse', minimal: 'Minimal', temperature: 'Temperatur', humidity: 'Luftfuktighet', co2: 'CO₂', presence: 'Tilstedeværelse', occupied: 'Registrert', clear: 'Ikke registrert', roomCaption: 'Ditt rom, akkurat nå', actions: 'Romkontroller', activate: 'Aktiver', sending: 'Sender …', action_1: 'Handling 1', action_2: 'Handling 2', action_3: 'Handling 3', action_1_label: 'Navn på handling 1', action_2_label: 'Navn på handling 2', action_3_label: 'Navn på handling 3' },
    en: { room: 'A little room to unwind.', roomKicker: 'Room control', lounge: 'Lounge', blueprint: 'Blueprint', minimal: 'Minimal', temperature: 'Temperature', humidity: 'Humidity', co2: 'CO₂', presence: 'Presence', occupied: 'Detected', clear: 'Not detected', roomCaption: 'Your room, right now', actions: 'Room controls', activate: 'Activate', sending: 'Sending …', action_1: 'Action 1', action_2: 'Action 2', action_3: 'Action 3', action_1_label: 'Action 1 name', action_2_label: 'Action 2 name', action_3_label: 'Action 3 name' },
  }, { width: 450, height: 650 }),
  energy: definition('energy', { style: 'diagram', accent: '#6f9164', solar: '', grid: '', battery: '', home: '', ev: '', soc: '', grid_direction: 'import', battery_direction: 'discharge' }, [
    option('style', ['diagram', 'orbit', 'ledger']),
    ...['solar', 'grid', 'battery', 'home', 'ev'].map((key) => entity(key, ['sensor'], { hint: key === 'home' ? 'homeHint' : key === 'ev' ? 'evHint' : 'powerHint' })),
    entity('soc', ['sensor'], { hint: 'socHint' }), option('grid_direction', ['import', 'export'], { hint: 'gridHint' }), option('battery_direction', ['discharge', 'charge'], { hint: 'batteryHint' }),
  ], {
    no: { energy: 'Energi i bevegelse.', energyKicker: 'Energy flow', diagram: 'Flytdiagram', orbit: 'Sirkler', ledger: 'Liste', solar: 'Sol', grid: 'Nett', battery: 'Batteri', home: 'Bolig', ev: 'Elbil', soc: 'Batteriprosent', powerHint: 'Effekt i W, kW eller MW. Ikke energi i kWh.', homeHint: 'Valgfritt. Uten måler beregnes summen av valgte sol-, nett- og batterimålere. Velg alle kilder for korrekt total.', evHint: 'Elbilladingen må inngå i boligens totale forbruk.', socHint: 'Valgfritt. Sensorens enhet må være %.', grid_direction: 'Positiv nettverdi betyr', battery_direction: 'Positiv batteriverdi betyr', gridHint: 'Bruk én nettomåler med fortegn for import og eksport.', batteryHint: 'Bruk én nettomåler med fortegn for lading og utlading.', import: 'Import fra nettet', export: 'Eksport til nettet', discharge: 'Batteriet leverer strøm', charge: 'Batteriet lades', importing: 'Import', exporting: 'Eksport', discharging: 'Leverer', charging: 'Lader', idle: 'Ingen flyt', measured: 'Målt', calculated: 'Beregnet', incomplete: 'Mangler målinger', unbalanced: 'Sjekk fortegn', notConfigured: 'Ikke valgt', invalidUnit: 'Ugyldig effektenhet', negativePower: 'Negativ verdi', includedHome: 'Inngår i bolig', chargeLevel: 'Nivå', energyNote: 'Effekt akkurat nå. Prikkene viser retningen på energiflyten.', calculatedNote: 'Bolig er beregnet fra valgte kilder. Elbil inngår i boligens total.', unbalancedNote: 'Kildene gir negativt forbruk. Sjekk målinger og fortegn i innstillingene.' },
    en: { energy: 'A home in balance.', energyKicker: 'Energy flow', diagram: 'Flow diagram', orbit: 'Orbits', ledger: 'Ledger', solar: 'Solar', grid: 'Grid', battery: 'Battery', home: 'Home', ev: 'EV', soc: 'Battery percentage', powerHint: 'Power in W, kW or MW. Not energy in kWh.', homeHint: 'Optional. Without a meter, adds the selected solar, grid and battery readings. Select every source for a correct total.', evHint: 'EV charging must already be included in total home consumption.', socHint: 'Optional. The sensor unit must be %.', grid_direction: 'Positive grid value means', battery_direction: 'Positive battery value means', gridHint: 'Use one signed net meter for import and export.', batteryHint: 'Use one signed net meter for charging and discharging.', import: 'Import from grid', export: 'Export to grid', discharge: 'Battery supplies power', charge: 'Battery charges', importing: 'Importing', exporting: 'Exporting', discharging: 'Supplying', charging: 'Charging', idle: 'No flow', measured: 'Measured', calculated: 'Calculated', incomplete: 'Missing readings', unbalanced: 'Check signs', notConfigured: 'Not selected', invalidUnit: 'Invalid power unit', negativePower: 'Negative reading', includedHome: 'Included in home', chargeLevel: 'Level', energyNote: 'Power right now. Moving dots show the direction of energy flow.', calculatedNote: 'Home is calculated from selected sources. EV is included in the home total.', unbalancedNote: 'Sources give negative consumption. Check readings and sign settings.' },
  }, { width: 460, height: 570 }),
};
